version: "2.0"
services:
  shortener:
    image: shortener
    ports:
      - "8080:3000"
    environment:
      - RAILS_ENV=development
  db:
    image: postgres:9.4
    volumes:
        - ./db/config.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=password
    ports:
    - "5432:5432"